branch-defaults:
  default:
    environment: null
    group_suffix: null
global:
  application_name: Sample-env
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: python3.4
  default_region: us-east-1
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: null
  workspace_type: Application
